# Generated by Django 3.2.6 on 2021-11-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_amount',
            name='related_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rented_product', to='Rent.product'),
        ),
    ]
