# Generated by Django 3.2.7 on 2021-09-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='subcategories',
        ),
    ]
