# Generated by Django 3.2.6 on 2021-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_alter_product_image_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(upload_to='title_photos'),
        ),
    ]
