# Generated by Django 3.2.6 on 2021-11-10 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('city', models.CharField(max_length=15)),
                ('PAN', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_acc_no', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('ifsc', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('address', models.TextField()),
                ('seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
