# Generated by Django 3.2.6 on 2021-09-08 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile_no',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
