# Generated by Django 3.2.6 on 2021-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_seller_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
